Repository Easy-Excel/EE_Server, pull requests merged in 2024-02, with the labels that each got.

#37 ♻️ [REFACTOR]: 범주 ENUM 멤버 추가 및 함수 예제 엔티티 컬럼 수정
  src/main/java/umc/easyexcel/converter/FunctionsExampleConverter.java
  src/main/java/umc/easyexcel/domain/enums/FunctionCategory.java
  src/main/java/umc/easyexcel/domain/mapping/FunctionsExample.java
  src/main/java/umc/easyexcel/web/dto/FunctionsExampleResponseDTO.java
Labels: :recycle: Refactoring

#40 [BUG FIX]: CORS 오류 해결
  README.md
  src/main/java/umc/easyexcel/config/WebConfig.java
Labels: :ambulance: Bug Fix

#44 ♻️ [REFACTOR]: 함수 예제 엔티티 컬럼 수정
  src/main/java/umc/easyexcel/domain/mapping/FunctionsExample.java
Labels: :recycle: Refactoring

#50 🐞 [BUG FIX]: CORS 오류 해결
  src/main/java/umc/easyexcel/config/WebConfig.java
Labels: :ambulance: Bug Fix

#51 🐞 [BUG FIX]: CORS 오류 해결
  src/main/java/umc/easyexcel/config/WebConfig.java
Labels: :ambulance: Bug Fix

#52 🎨 [FEAT]: 피드백 보내기 - 알림메일 추가
  build.gradle
  src/main/java/umc/easyexcel/domain/ShortcutKey.java
  src/main/java/umc/easyexcel/service/MailService/MailService.java
  src/main/java/umc/easyexcel/service/MailService/MailServiceImpl.java
  src/main/java/umc/easyexcel/web/controller/FeedbackRestController.java
  src/main/resources/application.yml
  src/main/resources/email-template.txt
Labels: :sparkles: Feat, :art: Update

#53 🐞 [BUG FIX]: CORS 오류 해결
  src/main/java/umc/easyexcel/config/WebConfig.java
Labels: :ambulance: Bug Fix
