Repository Easy-Excel/EE_Server, pull requests merged in 2024-01, with the labels that each got.

#10 ✨[FEAT]: 문자별 함수 리스트 조회 API
  src/main/java/umc/easyexcel/converter/FunctionsConverter.java
  src/main/java/umc/easyexcel/converter/TempConverter.java
  src/main/java/umc/easyexcel/repository/FunctionsRepository.java
  src/main/java/umc/easyexcel/repository/TempRepository.java
  src/main/java/umc/easyexcel/service/FunctionsService/FunctionsQueryService.java
  src/main/java/umc/easyexcel/service/FunctionsService/FunctionsQueryServiceImpl.java
  src/main/java/umc/easyexcel/service/TempService/TempCommandService.java
  src/main/java/umc/easyexcel/service/TempService/TempCommandServiceImpl.java
  src/main/java/umc/easyexcel/service/TempService/TempQueryService.java
  src/main/java/umc/easyexcel/service/TempService/TempQueryServiceImpl.java
  src/main/java/umc/easyexcel/web/controller/FunctionsRestController.java
  src/main/java/umc/easyexcel/web/controller/HelloController.java
  src/main/java/umc/easyexcel/web/dto/FunctionsResponseDTO.java
  src/main/java/umc/easyexcel/web/dto/TempRequest.java
Labels: :sparkles: Feat

#14 ✨ [FEAT]: 단축키 조회 API
  src/main/java/umc/easyexcel/apiPayload/exception/handler/TempHandler.java
  src/main/java/umc/easyexcel/converter/ShortcutKeyConverter.java
  src/main/java/umc/easyexcel/domain/ShortcutKey.java
  src/main/java/umc/easyexcel/domain/common/BaseEntity.java
  src/main/java/umc/easyexcel/domain/enums/ShortcutKeyCategory.java
  src/main/java/umc/easyexcel/domain/enums/TempEnum.java
  src/main/java/umc/easyexcel/repository/ShortcutKeyRepository.java
  src/main/java/umc/easyexcel/service/ShortcutKeyService/ShortcutKeyQueryService.java
  src/main/java/umc/easyexcel/service/ShortcutKeyService/ShortcutKeyQueryServiceImpl.java
  src/main/java/umc/easyexcel/validation/annotation/TempAnnotation.java
  src/main/java/umc/easyexcel/validation/validator/TempValidator.java
  src/main/java/umc/easyexcel/web/controller/ShortcutKeyController.java
  src/main/java/umc/easyexcel/web/dto/ShortcutKeyResponseDto.java
Labels: :sparkles: Feat

#15 ✨ [FEAT]: 함수 설명 조회 API
  src/main/java/umc/easyexcel/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/easyexcel/apiPayload/exception/handler/FunctionsHandler.java
  src/main/java/umc/easyexcel/converter/FunctionsConverter.java
  src/main/java/umc/easyexcel/domain/mapping/FunctionsValue.java
  src/main/java/umc/easyexcel/repository/FunctionsValueRepository.java
  src/main/java/umc/easyexcel/repository/ValueRepository.java
  src/main/java/umc/easyexcel/service/FunctionsService/FunctionsService.java
  src/main/java/umc/easyexcel/service/FunctionsService/FunctionsServiceImpl.java
  src/main/java/umc/easyexcel/web/dto/FunctionsResponseDTO.java
  src/main/java/umc/easyexcel/web/dto/ValueDTO.java
Labels: :sparkles: Feat

#18 ✨ [FEAT]: 피드백 API
  src/main/java/umc/easyexcel/converter/FeedbackConverter.java
  src/main/java/umc/easyexcel/domain/ExampleExplanation.java
  src/main/java/umc/easyexcel/domain/ExampleTip.java
  src/main/java/umc/easyexcel/domain/FeatureCharacteristic.java
  src/main/java/umc/easyexcel/domain/Feedback.java
  src/main/java/umc/easyexcel/domain/Functions.java
  src/main/java/umc/easyexcel/domain/ShortcutKey.java
  src/main/java/umc/easyexcel/domain/common/BaseEntity.java
  src/main/java/umc/easyexcel/domain/mapping/FunctionsExample.java
  src/main/java/umc/easyexcel/repository/FeedbackRepository.java
  src/main/java/umc/easyexcel/service/FeedbackService/FeedbackService.java
  src/main/java/umc/easyexcel/service/FeedbackService/FeedbackServiceImpl.java
  src/main/java/umc/easyexcel/web/controller/FeedbackRestController.java
  src/main/java/umc/easyexcel/web/dto/FeedbackRequestDTO.java
  src/main/java/umc/easyexcel/web/dto/FeedbackResponseDTO.java
Labels: :sparkles: Feat

#20 🎨 [UPDATE] 단축키 검색 시 대소문자 구분X
  src/main/java/umc/easyexcel/converter/ShortcutKeyConverter.java
  src/main/java/umc/easyexcel/domain/mapping/FunctionsExample.java
  src/main/java/umc/easyexcel/repository/ShortcutKeyRepository.java
  src/main/java/umc/easyexcel/service/ShortcutKeyService/ShortcutKeyQueryService.java
  src/main/java/umc/easyexcel/service/ShortcutKeyService/ShortcutKeyQueryServiceImpl.java
  src/main/java/umc/easyexcel/web/controller/ShortcutKeyController.java
  src/main/java/umc/easyexcel/web/dto/ShortcutKeyResponseDto.java
Labels: :art: Update

#22 [UPDATE] 카테고리 ENUM으로 변경
  src/main/java/umc/easyexcel/converter/CategoryConverter.java
  src/main/java/umc/easyexcel/domain/Functions.java
  src/main/java/umc/easyexcel/domain/enums/FunctionCategory.java
  src/main/java/umc/easyexcel/repository/CategoryRepository.java
  src/main/java/umc/easyexcel/service/CategoryService/CategoryService.java
  src/main/java/umc/easyexcel/service/CategoryService/CategoryServiceImpl.java
  src/main/java/umc/easyexcel/web/controller/CategoryRestController.java
Labels: :art: Update

#24 🎨 [UPDATE]: 함수 예제 조회 API - 예외 처리 구현
  src/main/java/umc/easyexcel/service/FunctionsExampleService/FunctionsExampleServiceImpl.java
  src/main/java/umc/easyexcel/web/controller/FunctionsExampleRestController.java
Labels: :art: Update

#28 🎨 [UPDATE] 단축키 조회/검색 - 예외 처리 추가
  src/main/java/umc/easyexcel/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/easyexcel/apiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/easyexcel/apiPayload/exception/handler/ShortcutKeyHandler.java
  src/main/java/umc/easyexcel/web/controller/ShortcutKeyController.java
Labels: :art: Update

#30 ♻️ [REFACTOR]: 함수 예제 조회 API - URL 통일을 위한 컨트롤러 리팩토링
  src/main/java/umc/easyexcel/web/controller/FunctionsExampleRestController.java
  src/main/java/umc/easyexcel/web/controller/FunctionsRestController.java
Labels: :recycle: Refactoring

#32 ♻️ [REFACTOR]: 범주별 함수 리스트 조회 API - URL 통일을 위한 컨트롤러 리팩토링
  src/main/java/umc/easyexcel/web/controller/CategoryRestController.java
  src/main/java/umc/easyexcel/web/controller/FunctionsRestController.java
Labels: :recycle: Refactoring

#34 🎨 [UPDATE] 단축키 검색 - 유사 단어 매핑 추가
  src/main/java/umc/easyexcel/repository/SimilarWordsRepository.java
  src/main/java/umc/easyexcel/service/ShortcutKeyService/ShortcutKeyQueryServiceImpl.java
  src/main/java/umc/easyexcel/web/controller/FrequentFeatureRestController.java
  src/main/java/umc/easyexcel/web/controller/ShortcutKeyRestController.java
Labels: :art: Update
